# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Fetch and generate data.

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm ci

    - name: Generate data
      env:
          AUTH: ${{ secrets.AUTH_GITHUB_TOKEN }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          REPO_LABELS: ${{ secrets.REPO_LABELS }}
      run: |
        AUTH="$AUTH" USER_AGENT="$USER_AGENT" REPO_OWNER="$REPO_OWNER" REPO_NAME="$REPO_NAME" REPO_LABELS="$REPO_LABELS" npm run generate

    - name: Commit files
      run: |
        git config --local user.email "simpleplan.vn@gmail.com"
        git config --local user.name "Automated Action"
        git add data/*/*.json
        git commit -m "Automated Data Update"  || exit 0

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
        github_token: ${{ secrets.AUTH_GITHUB_TOKEN }}
      
